#!/bin/sh
# wpilog-mcp installer for macOS/Linux
# Usage: curl -fsSL https://raw.githubusercontent.com/TripleHelixProgramming/wpilog-mcp/main/install.sh | sh
set -e

REPO="TripleHelixProgramming/wpilog-mcp"
INSTALL_DIR="$HOME/.wpilog-mcp"

echo ""
echo "========================================"
echo "  wpilog-mcp Installer"
echo "========================================"
echo ""

# --- Find Java ---

find_java() {
    # 1. WPILib JDK (scan for latest year)
    if [ -d "$HOME/wpilib" ]; then
        for year in $(ls -1rd "$HOME/wpilib"/[0-9][0-9][0-9][0-9] 2>/dev/null); do
            if [ -x "$year/jdk/bin/java" ]; then
                echo "Found WPILib $(basename "$year") JDK: $year/jdk/bin/java" >&2
                echo "$year/jdk/bin/java"
                return 0
            fi
        done
    fi

    # 2. JAVA_HOME
    if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
        echo "Found JAVA_HOME: $JAVA_HOME/bin/java" >&2
        echo "$JAVA_HOME/bin/java"
        return 0
    fi

    # 3. System PATH
    if command -v java >/dev/null 2>&1; then
        echo "Found java on PATH: $(command -v java)" >&2
        command -v java
        return 0
    fi

    echo "ERROR: Java 17+ is required but not found." >&2
    echo "Install the WPILib toolkit: https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html" >&2
    exit 1
}

JAVA_EXEC=$(find_java)

# Verify Java version
JAVA_VERSION=$("$JAVA_EXEC" -version 2>&1 | head -1)
echo "Java version: $JAVA_VERSION"
echo ""

# --- Download latest release ---

echo "Fetching latest release from GitHub..."
RELEASE_JSON=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" -H "User-Agent: wpilog-mcp-installer")
VERSION=$(echo "$RELEASE_JSON" | grep '"tag_name"' | sed 's/.*"v\([^"]*\)".*/\1/')
JAR_URL=$(echo "$RELEASE_JSON" | grep '"browser_download_url".*-all\.jar"' | sed 's/.*"\(https[^"]*\)".*/\1/')

if [ -z "$JAR_URL" ]; then
    echo "ERROR: No JAR asset found in latest release" >&2
    exit 1
fi

# The version names files below, so it must look like one
case "$VERSION" in
    ""|*[!0-9A-Za-z.-]*)
        echo "ERROR: The latest release's tag is not a version: $VERSION" >&2
        exit 1
        ;;
esac

echo "Latest version: $VERSION"
echo ""

# --- Create directory structure ---

JARS_DIR="$INSTALL_DIR/jars"
BIN_DIR="$INSTALL_DIR/bin"
mkdir -p "$JARS_DIR" "$BIN_DIR"

# --- Download JAR ---

JAR_NAME="wpilog-mcp-${VERSION}.jar"
JAR_PATH="$JARS_DIR/$JAR_NAME"

if [ -f "$JAR_PATH" ]; then
    echo "JAR already exists: $JAR_PATH"
else
    echo "Downloading $JAR_NAME..."
    curl -fsSL -o "$JAR_PATH" "$JAR_URL"
    echo "Downloaded: $JAR_PATH"
fi

# --- Create launchers ---
# As ./gradlew install does: a launcher for this version, and wpilog-mcp, a symlink to it.
# Earlier versions' launchers and JARs stay until you delete them.

SCRIPT_PATH="$BIN_DIR/wpilog-mcp-$VERSION"
{
echo "#!/bin/sh"
echo "# wpilog-mcp $VERSION launcher"
echo "# Auto-generated by install.sh"
cat << 'LAUNCHER'

MAX_HEAP="${WPILOG_MAX_HEAP:-4g}"

# Prefer WPILib JDK (scan for latest year), then JAVA_HOME, then system java
JAVA_EXEC="java"
if [ -d "$HOME/wpilib" ]; then
    for year in $(ls -1rd "$HOME/wpilib"/[0-9][0-9][0-9][0-9] 2>/dev/null); do
        if [ -x "$year/jdk/bin/java" ]; then
            JAVA_EXEC="$year/jdk/bin/java"
            break
        fi
    done
fi
if [ "$JAVA_EXEC" = "java" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA_EXEC="$JAVA_HOME/bin/java"
fi

LAUNCHER
# The jar path, outside the quoted heredoc so that it expands
echo "exec \"\$JAVA_EXEC\" -Xmx\"\$MAX_HEAP\" -jar \"$JAR_PATH\" \"\$@\""
} > "$SCRIPT_PATH"
chmod +x "$SCRIPT_PATH"
echo "Created launcher: $SCRIPT_PATH"

# Replace wpilog-mcp itself (an earlier launcher or symlink), never write through it
CURRENT_PATH="$BIN_DIR/wpilog-mcp"
rm -f "$CURRENT_PATH"
ln -s "wpilog-mcp-$VERSION" "$CURRENT_PATH"
echo "Updated symlink: $CURRENT_PATH -> wpilog-mcp-$VERSION"

# --- Create default config ---

CONFIG_PATH="$INSTALL_DIR/servers.yaml"
if [ ! -f "$CONFIG_PATH" ]; then
    cat > "$CONFIG_PATH" << 'CONFIG'
# wpilog-mcp server configuration
# Documentation: https://github.com/TripleHelixProgramming/wpilog-mcp/blob/main/doc/STANDALONE.md#configuration

# ---- Defaults ----
# Top-level settings are inherited by all server configurations below.
# Individual servers can override any of these.

# Your FRC team number, for The Blue Alliance match data when a log does not record one.
# Remove the # and put in your number:
# team: 1234

# Directory containing .wpilog files downloaded from the roboRIO
logdir: ~/riologs
# Or several directories, listed together:
# logdir:
#   - ~/riologs
#   - /Volumes/LOGS/archive

# The Blue Alliance API key (get one at https://www.thebluealliance.com/account).
# Remove the # and put in your key, or set the TBA_API_KEY environment variable instead:
# tba_key: your-key-here

# ---- Server Configurations ----
servers:

  # Default: stdio transport for MCP clients (Claude Desktop, etc.)
  default:
    transport: stdio

  # HTTP transport for browser-based or multi-client access
  http:
    transport: http
    port: 2363

  # For the project's stress tests (./gradlew stressTest), with the settings above
  stresstest: {}
CONFIG
    echo "Created default config: $CONFIG_PATH"
    echo "  Edit this file to set your team number and log directory."
else
    echo "Config already exists: $CONFIG_PATH (not overwritten)"
fi

# --- PATH instructions ---

echo ""
echo "========================================"
echo "  Installation complete!"
echo "========================================"
echo ""

case ":$PATH:" in
    *":$BIN_DIR:"*)
        echo "bin directory is already on your PATH."
        ;;
    *)
        echo "Add to your shell profile (~/.zshrc or ~/.bashrc):"
        echo ""
        echo "  export PATH=\"\$HOME/.wpilog-mcp/bin:\$PATH\""
        echo ""
        echo "Then restart your terminal."
        ;;
esac

echo ""
echo "Usage:"
echo "  wpilog-mcp                    Start MCP server (stdio)"
echo "  wpilog-mcp start http         Start HTTP daemon"
echo ""
