# wpilog-mcp installer for Windows
# Usage: irm https://raw.githubusercontent.com/TripleHelixProgramming/wpilog-mcp/main/install.ps1 | iex

$ErrorActionPreference = "Stop"
$repo = "TripleHelixProgramming/wpilog-mcp"
$installDir = Join-Path $env:USERPROFILE ".wpilog-mcp"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  wpilog-mcp Installer" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# --- Find Java ---

function Find-Java {
    # 1. WPILib JDK (scan for latest year)
    $wpilibDirs = @(
        (Join-Path $env:USERPROFILE "wpilib"),
        "C:\Users\Public\wpilib"
    )
    foreach ($base in $wpilibDirs) {
        if (Test-Path $base) {
            $years = Get-ChildItem -Path $base -Directory | Where-Object { $_.Name -match '^\d{4}$' } | Sort-Object Name -Descending
            foreach ($year in $years) {
                $javaExe = Join-Path $year.FullName "jdk\bin\java.exe"
                if (Test-Path $javaExe) {
                    Write-Host "Found WPILib $($year.Name) JDK: $javaExe" -ForegroundColor Green
                    return $javaExe
                }
            }
        }
    }

    # 2. JAVA_HOME
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\java.exe"))) {
        $javaExe = Join-Path $env:JAVA_HOME "bin\java.exe"
        Write-Host "Found JAVA_HOME: $javaExe" -ForegroundColor Green
        return $javaExe
    }

    # 3. System PATH
    $javaCmd = Get-Command java -ErrorAction SilentlyContinue
    if ($javaCmd) {
        Write-Host "Found java on PATH: $($javaCmd.Source)" -ForegroundColor Green
        return $javaCmd.Source
    }

    Write-Host "ERROR: Java 17+ is required but not found." -ForegroundColor Red
    Write-Host "Install the WPILib toolkit: https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html" -ForegroundColor Yellow
    exit 1
}

$javaExe = Find-Java

# Show the Java version. java -version writes to stderr, which Windows PowerShell 5.1 turns into
# an error that stops the script when $ErrorActionPreference is Stop.
$ErrorActionPreference = "Continue"
$versionOutput = & $javaExe -version 2>&1 | Select-Object -First 1
$ErrorActionPreference = "Stop"
Write-Host "Java version: $versionOutput"
Write-Host ""

# --- Download latest release ---

# GitHub needs TLS 1.2, which Windows PowerShell 5.1 may not offer by default
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

Write-Host "Fetching latest release from GitHub..." -ForegroundColor Cyan
$releaseInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/releases/latest" -Headers @{ "User-Agent" = "wpilog-mcp-installer" }
$version = $releaseInfo.tag_name -replace '^v', ''
$jarAsset = $releaseInfo.assets | Where-Object { $_.name -like "*-all.jar" } | Select-Object -First 1

if (-not $jarAsset) {
    Write-Host "ERROR: No JAR asset found in release $($releaseInfo.tag_name)" -ForegroundColor Red
    exit 1
}

# The version names files below, so it must look like one
if ($version -notmatch '^[0-9A-Za-z.-]+$') {
    Write-Host "ERROR: The latest release's tag is not a version: $($releaseInfo.tag_name)" -ForegroundColor Red
    exit 1
}

Write-Host "Latest version: $version" -ForegroundColor Green
Write-Host ""

# --- Create directory structure ---

$jarsDir = Join-Path $installDir "jars"
$binDir = Join-Path $installDir "bin"
New-Item -ItemType Directory -Path $jarsDir -Force | Out-Null
New-Item -ItemType Directory -Path $binDir -Force | Out-Null

# --- Download JAR ---

$jarName = "wpilog-mcp-${version}.jar"
$jarPath = Join-Path $jarsDir $jarName

if (Test-Path $jarPath) {
    Write-Host "JAR already exists: $jarPath" -ForegroundColor Yellow
} else {
    Write-Host "Downloading $($jarAsset.name)..." -ForegroundColor Cyan
    Invoke-WebRequest -Uri $jarAsset.browser_download_url -OutFile $jarPath -UseBasicParsing
    Write-Host "Downloaded: $jarPath" -ForegroundColor Green
}

# --- Create launchers ---
# As ./gradlew install does: a launcher for this version, and wpilog-mcp.bat, a copy of it.
# Earlier versions' launchers and JARs stay until you delete them.

$batContent = @"
@echo off
setlocal EnableDelayedExpansion
REM wpilog-mcp $version launcher
REM Auto-generated by install.ps1

REM Memory management is automatic. Set WPILOG_MAX_HEAP to control heap size.
set MAX_HEAP=%WPILOG_MAX_HEAP%
if "%MAX_HEAP%"=="" set MAX_HEAP=4g

REM Prefer WPILib JDK if available (scans for latest year)
set JAVA_EXEC=java
set WPILIB_FOUND=0
for /f "tokens=*" %%D in ('dir /b /ad /o-n "%USERPROFILE%\wpilib" 2^>nul') do (
    if "!WPILIB_FOUND!"=="0" if exist "%USERPROFILE%\wpilib\%%D\jdk\bin\java.exe" (
        set JAVA_EXEC=%USERPROFILE%\wpilib\%%D\jdk\bin\java.exe
        set WPILIB_FOUND=1
    )
)
if "!WPILIB_FOUND!"=="0" (
    for /f "tokens=*" %%D in ('dir /b /ad /o-n "C:\Users\Public\wpilib" 2^>nul') do (
        if "!WPILIB_FOUND!"=="0" if exist "C:\Users\Public\wpilib\%%D\jdk\bin\java.exe" (
            set JAVA_EXEC=C:\Users\Public\wpilib\%%D\jdk\bin\java.exe
            set WPILIB_FOUND=1
        )
    )
)

"%JAVA_EXEC%" -Xmx%MAX_HEAP% -jar "$($jarsDir.Replace('/', '\'))\$jarName" %*
"@
# cmd.exe reads batch files with CRLF line endings
$batContent = $batContent -replace "`r?`n", "`r`n"

$batPath = Join-Path $binDir "wpilog-mcp-$version.bat"
[System.IO.File]::WriteAllText($batPath, $batContent, [System.Text.Encoding]::ASCII)
Write-Host "Created launcher: $batPath" -ForegroundColor Green

$currentBat = Join-Path $binDir "wpilog-mcp.bat"
Copy-Item -Path $batPath -Destination $currentBat -Force
Write-Host "Updated current: $currentBat" -ForegroundColor Green

# --- Create default config ---

$configPath = Join-Path $installDir "servers.yaml"
if (-not (Test-Path $configPath)) {
    # Single-quoted, so that PowerShell expands nothing in it
    $configContent = @'
# wpilog-mcp server configuration
# Documentation: https://github.com/TripleHelixProgramming/wpilog-mcp/blob/main/doc/STANDALONE.md#configuration

# ---- Defaults ----
# Top-level settings are inherited by all server configurations below.
# Individual servers can override any of these.

# Your FRC team number, for The Blue Alliance match data when a log does not record one.
# Remove the # and put in your number:
# team: 1234

# Directory containing .wpilog files downloaded from the roboRIO
logdir: ~/riologs
# Or several directories, listed together:
# logdir:
#   - ~/riologs
#   - D:/frc-logs/archive

# The Blue Alliance API key (get one at https://www.thebluealliance.com/account).
# Remove the # and put in your key, or set the TBA_API_KEY environment variable instead:
# tba_key: your-key-here

# ---- Server Configurations ----
servers:

  # Default: stdio transport for MCP clients (Claude Desktop, etc.)
  default:
    transport: stdio

  # HTTP transport for browser-based or multi-client access
  http:
    transport: http
    port: 2363

  # For the project's stress tests (./gradlew stressTest), with the settings above
  stresstest: {}
'@
    # UTF-8 without a byte order mark (Set-Content -Encoding UTF8 adds one in Windows PowerShell)
    [System.IO.File]::WriteAllText($configPath, $configContent + "`n")
    Write-Host "Created default config: $configPath" -ForegroundColor Green
    Write-Host "  Edit this file to set your team number and log directory." -ForegroundColor Yellow
} else {
    Write-Host "Config already exists: $configPath (not overwritten)" -ForegroundColor Yellow
}

# --- PATH instructions ---

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if already on PATH
$currentPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($currentPath -notlike "*$binDir*") {
    Write-Host "Add to your PATH (run this once):" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  [Environment]::SetEnvironmentVariable('Path', `$env:Path + ';$binDir', 'User')" -ForegroundColor White
    Write-Host ""
    Write-Host "Then restart your terminal." -ForegroundColor Yellow
} else {
    Write-Host "bin directory is already on your PATH." -ForegroundColor Green
}

Write-Host ""
Write-Host "Usage:" -ForegroundColor Cyan
Write-Host "  wpilog-mcp                    Start MCP server (stdio)" -ForegroundColor White
Write-Host "  wpilog-mcp start http         Start HTTP daemon" -ForegroundColor White
Write-Host ""
Write-Host "VS Code MCP setup - add to .vscode/mcp.json:" -ForegroundColor Cyan
Write-Host @"
  {
    "servers": {
      "wpilog": {
        "command": "$($currentBat.Replace('\', '\\'))",
        "args": []
      }
    }
  }
"@ -ForegroundColor White
Write-Host ""
