@echo off
setlocal EnableDelayedExpansion
REM wpilog-mcp @VERSION@ launcher
REM Generated by wpilog-mcp install. Older versioned launchers keep their own JAR.

REM Memory management is automatic. Set WPILOG_MAX_HEAP to control heap size.
set MAX_HEAP=%WPILOG_MAX_HEAP%
if "%MAX_HEAP%"=="" set MAX_HEAP=4g

REM Prefer WPILib JDK if available (scans for latest year)
set JAVA_EXEC=java
set WPILIB_FOUND=0
set WPILIB_YEAR=0000
for %%B in ("%USERPROFILE%\wpilib" "C:\Users\Public\wpilib") do (
    for /f "tokens=*" %%D in ('dir /b /ad /o-n "%%~B" 2^>nul ^| findstr /r /x "[0-9][0-9][0-9][0-9]"') do (
        if "%%D" GTR "!WPILIB_YEAR!" if exist "%%~B\%%D\jdk\bin\java.exe" (
            set "JAVA_EXEC=%%~B\%%D\jdk\bin\java.exe"
            set WPILIB_YEAR=%%D
            set WPILIB_FOUND=1
        )
    )
)

if "!WPILIB_FOUND!"=="0" if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" set "JAVA_EXEC=%JAVA_HOME%\bin\java.exe"
setlocal DisableDelayedExpansion
"%JAVA_EXEC%" -Xmx%MAX_HEAP% -jar "%~dp0..\jars\wpilog-mcp-@VERSION@.jar" %*
exit /b %ERRORLEVEL%
