#!/bin/sh
# wpilog-mcp @VERSION@ launcher
# Generated by wpilog-mcp install. Older versioned launchers keep their own JAR.

MAX_HEAP="${WPILOG_MAX_HEAP:-4g}"
JAVA_EXEC="java"
# Globs keep paths with spaces intact; four-digit years sort oldest to newest.
for year in "$HOME"/wpilib/[0-9][0-9][0-9][0-9]; do
    if [ -x "$year/jdk/bin/java" ]; then
        JAVA_EXEC="$year/jdk/bin/java"
    fi
done
if [ "$JAVA_EXEC" = "java" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA_EXEC="$JAVA_HOME/bin/java"
fi
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec "$JAVA_EXEC" -Xmx"$MAX_HEAP" -jar "$SCRIPT_DIR/../jars/wpilog-mcp-@VERSION@.jar" "$@"
