/*
 * Copyright (c) 2026 Christopher Larrieu and Triple Helix Robotics
 * SPDX-License-Identifier: MIT
 */
package org.triplehelix.wpilogmcp.log;

import static org.junit.jupiter.api.Assertions.*;
import com.google.gson.JsonObject;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.triplehelix.wpilogmcp.capture.*;
import org.triplehelix.wpilogmcp.fixtures.WpilogWriter;
import org.triplehelix.wpilogmcp.nt4.ControlMessage.Announce;
import org.triplehelix.wpilogmcp.nt4.ValueFrame;
import org.triplehelix.wpilogmcp.nt4.client.*;
import org.triplehelix.wpilogmcp.store.*;

/** Opt-in, generated bytes only: exercises real storage, long file addresses and a wide rollover. */
@Tag("large-log")
class LargeLogTest {
  @TempDir Path temp;
  @Test void twoPointTwoGBLoadsImportsAndCaptureRollsBeyondTwoGiB() throws Exception {
    var source = temp.resolve("large.wpilog"); var payload = new byte[1 << 20];
    int records = 2100; // 2,202,009,600 payload bytes, without a giant heap allocation.
    try (var w = new WpilogWriter(source, "synthetic repeated records")) {
      int data = w.start("/payload", "raw", "", 0);
      for (int i = 0; i < records; i++) w.append(data, i * 1_000_000L, payload);
      int last = w.start("/last", "int64", "", records * 1_000_000L);
      w.append(last, records * 1_000_000L, WpilogWriter.encodeInt64(records));
    }
    long originalSize = Files.size(source); assertTrue(originalSize > 2_200_000_000L);
    var manager = new LogManager(); manager.addAllowedDirectory(temp);
    try (var stores = new StoreRegistry(manager.testGetSecurityValidator(), manager)) {
      try (var use = manager.acquire(source.toString())) {
        assertEquals(records, use.log().sampleCount("/payload"));
        assertEquals((long) records, use.log().values().get("/last").get(0).value());
      }
      var placed = stores.store(temp.resolve("store")).importPaths(new LogStore.Request(List.of(source), true, "synthetic"), p -> {})
          .get(120, TimeUnit.SECONDS).files().get(0);
      assertNotEquals("refused", placed.status(), placed::toString); assertFalse(Files.exists(source));
      assertEquals(originalSize, Files.size(placed.path()));
      var files = new ArrayList<Path>(); var first = temp.resolve("capture.wpilog");
      var index = new CaptureIndex(new CaptureWriter.Observer() {
        @Override public Path create(String address, Instant start) { return first; }
        @Override public void opened(CaptureWriter.Session session, boolean resumed) { files.add(session.path()); }
      }, manager, 0);
      var loop = new ManualScheduler(); long bound = (1L << 31) + (1L << 24);
      try (var writer = new CaptureWriter(Clock.systemUTC(), loop, CapturePolicy.ALL, index, bound)) {
        var topic = new Announce("/payload", 1, "raw", null, new JsonObject());
        writer.connected(RobotAddress.uri("127.0.0.1", 5810, "large"), "v4.0.networktables.first.wpi.edu");
        writer.timeSync(0, 0); writer.announce(topic);
        for (int i = 0; i < records; i++) {
          writer.value(topic, new ValueFrame(1, i * 1_000_000L, 5, payload), loop.nowUs());
          if (i % 64 == 63) index.live().expire();
        }
        var last = new Announce("/last", 2, "int", null, new JsonObject()); writer.announce(last);
        writer.value(last, new ValueFrame(2, records * 1_000_000L, 2, (long) records), loop.nowUs());
        assertNull(writer.session().endReason()); writer.disconnected();
        assertEquals((long) records, index.live().values().get("NT:/last").get(0).value());
      }
      assertEquals(2, files.size()); assertTrue(Files.size(first) > Integer.MAX_VALUE);
      int copied = 0;
      for (var file : files) {
        assertTrue(Files.size(file) <= bound);
        try (var use = manager.acquire(file.toString())) { copied += use.log().sampleCount("NT:/payload"); }
      }
      assertEquals(records, copied);
      var report = Path.of("build/reports/large-log/report.txt"); Files.createDirectories(report.getParent());
      Files.writeString(report, "fixture_bytes=" + originalSize + " records=" + records + " capture_files=" + files.size()
          + " first_capture_bytes=" + Files.size(first) + "\n");
    } finally { manager.shutdown(); }
  }
}
